openapi: 3.0.1
info:
  title: Agent Communication Protocol
  description: Specification of the API protocol for communication with an agent.
  version: 'v1'

paths:
  /agent/tasks:
    post:
      summary: Creates a new task for the agent to execute.
      tags: [agent, tasks]
      operationId: createAgentTask
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AgentTaskRequestBody'
      responses:
        200:
          description: A new agent task was successfuly created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AgentTask'
        default:
          description: Internal Server Error
    get:
      summary: List all tasks that have been created for the agent.
      tags: [agent, tasks]
      operationId: listAgentTasksIDs
      responses:
        200:
          description: Returned list of agent's task IDs.
          content:
            application/json:
              schema:
                type: array
                description: A list of task IDs
                items:
                  type: string
        default:
          description: Internal Server Error

  /agent/tasks/{task_id}:
    get:
      summary: Get details about a specified agent task.
      tags: [agent, tasks]
      operationId: getAgentTask
      parameters:
        - name: task_id
          in: path
          description: ID of the task
          required: true
          schema:
            type: string
      responses:
        200:
          description: Returned details about an agent task.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AgentTask'
        default:
          description: Internal Server Error

  /agent/tasks/{task_id}/step:
    post:
      summary: Execute a step in the specified agent task.
      tags: [agent, tasks, step]
      operationId: executeAgentTaskStep
      parameters:
        - name: task_id
          in: path
          description: ID of the task
          required: true
          schema:
            type: string
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AgentTaskRequestBody'
      responses:
        200:
          description: Executed step for the agent task.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AgentStepResult'
        default:
          description: Internal Server Error

components:
  schemas:
    AgentTaskInput:
      description: Input parameters for the task. This can be any JSON serializable object.
      type: object

    AgentStepArtifacts:
      description: Artifacts that the task has produced. This can be any JSON serializable object.
      type: object

    AgentStepOutput:
      description: Output of the task. This can be any JSON serializable object.
      type: object

    AgentTaskRequestBody:
      type: object
      description: Body of the task request.
      properties:
        input:
          $ref: "#/components/schemas/AgentTaskInput"

    AgentTask:
      type: object
      description: Wrapper containing the task.
      properties:
        task_id:
          description: The ID of the task.
          type: string
        input:
          $ref: "#/components/schemas/AgentTaskInput"

    AgentStepRequestBody:
      type: object
      description: Body of the task request.
      properties:
        input:
          $ref: "#/components/schemas/AgentTaskInput"

    AgentStepResult:
      description: Wrapper containing the result of the step.
      allOf:
        - $ref: '#/components/schemas/AgentTask'
        - type: object
          properties:
            output:
              $ref: "#/components/schemas/AgentStepOutput"
            artifacts:
              $ref: "#/components/schemas/AgentStepArtifacts"